import type { CrossingEntity, LegacyCrossingRecommendation, BorderAlertEvent } from "@/types";

// ─── Mock Data: Crossings ───
export const MOCK_CROSSINGS: CrossingEntity[] = [
  {
    id: "san-ysidro",
    name: "San Ysidro",
    cityOrigin: "Tijuana",
    cityDestination: "San Diego",
    direction: "MX_TO_US",
    status: "OPEN",
    is24Hours: true,
    operatingHoursText: "Open 24 hours",
    lanes: {
      STANDARD: {
        program: "STANDARD",
        isOpen: true,
        lanesOpenCount: 8,
        totalLanesCount: 10,
        currentWaitMinutes: 45,
        trend: "WORSENING",
      },
      READY_LANE: {
        program: "READY_LANE",
        isOpen: true,
        lanesOpenCount: 3,
        totalLanesCount: 4,
        currentWaitMinutes: 22,
        trend: "STABLE",
      },
      SENTRI: {
        program: "SENTRI",
        isOpen: true,
        lanesOpenCount: 2,
        totalLanesCount: 2,
        currentWaitMinutes: 8,
        trend: "IMPROVING",
      },
      PEDESTRIAN: {
        program: "PEDESTRIAN",
        isOpen: true,
        lanesOpenCount: 2,
        totalLanesCount: 2,
        currentWaitMinutes: 30,
        trend: "STABLE",
      },
      COMMERCIAL: {
        program: "COMMERCIAL",
        isOpen: true,
        lanesOpenCount: 3,
        totalLanesCount: 4,
        currentWaitMinutes: 60,
        trend: "WORSENING",
      },
    },
    dominantWaitMinutes: 45,
    typicalWaitMinutes: 35,
    lastUpdated: new Date(Date.now() - 60000).toISOString(),
    coordinates: { lat: 32.5431, lng: -117.0379 },
    restrictions: {
      commercialAllowed: true,
      pedestrianAllowed: true,
    },
    historicalHourlyProfile: Array.from({ length: 24 }, (_, i) => ({
      hour: i,
      typicalWait: Math.round(20 + 40 * Math.sin((i - 6) * (Math.PI / 12))),
      todayActualWait: undefined,
    })),
  },
  {
    id: "otay-mesa",
    name: "Otay Mesa",
    cityOrigin: "Tijuana",
    cityDestination: "San Diego",
    direction: "MX_TO_US",
    status: "OPEN",
    is24Hours: true,
    operatingHoursText: "Open 24 hours",
    lanes: {
      STANDARD: {
        program: "STANDARD",
        isOpen: true,
        lanesOpenCount: 5,
        totalLanesCount: 6,
        currentWaitMinutes: 35,
        trend: "STABLE",
      },
      READY_LANE: {
        program: "READY_LANE",
        isOpen: true,
        lanesOpenCount: 2,
        totalLanesCount: 2,
        currentWaitMinutes: 18,
        trend: "IMPROVING",
      },
      SENTRI: {
        program: "SENTRI",
        isOpen: true,
        lanesOpenCount: 2,
        totalLanesCount: 2,
        currentWaitMinutes: 5,
        trend: "STABLE",
      },
      PEDESTRIAN: {
        program: "PEDESTRIAN",
        isOpen: false,
        currentWaitMinutes: 0,
        trend: "STABLE",
      },
      COMMERCIAL: {
        program: "COMMERCIAL",
        isOpen: true,
        lanesOpenCount: 4,
        totalLanesCount: 4,
        currentWaitMinutes: 25,
        trend: "IMPROVING",
      },
    },
    dominantWaitMinutes: 35,
    typicalWaitMinutes: 28,
    lastUpdated: new Date(Date.now() - 120000).toISOString(),
    coordinates: { lat: 32.5561, lng: -116.9756 },
    restrictions: {
      commercialAllowed: true,
      pedestrianAllowed: false,
    },
    historicalHourlyProfile: Array.from({ length: 24 }, (_, i) => ({
      hour: i,
      typicalWait: Math.round(15 + 30 * Math.sin((i - 6) * (Math.PI / 12))),
    })),
  },
  {
    id: "tecate",
    name: "Tecate",
    cityOrigin: "Tecate",
    cityDestination: "Tecate",
    direction: "MX_TO_US",
    status: "LIMITED",
    is24Hours: false,
    operatingHoursText: "6:00 AM – 10:00 PM",
    lanes: {
      STANDARD: {
        program: "STANDARD",
        isOpen: true,
        lanesOpenCount: 2,
        totalLanesCount: 2,
        currentWaitMinutes: 15,
        trend: "STABLE",
      },
      READY_LANE: {
        program: "READY_LANE",
        isOpen: false,
        currentWaitMinutes: 0,
        trend: "STABLE",
      },
      SENTRI: {
        program: "SENTRI",
        isOpen: false,
        currentWaitMinutes: 0,
        trend: "STABLE",
      },
      PEDESTRIAN: {
        program: "PEDESTRIAN",
        isOpen: true,
        lanesOpenCount: 1,
        totalLanesCount: 1,
        currentWaitMinutes: 10,
        trend: "STABLE",
      },
      COMMERCIAL: {
        program: "COMMERCIAL",
        isOpen: true,
        lanesOpenCount: 1,
        totalLanesCount: 1,
        currentWaitMinutes: 20,
        trend: "STABLE",
      },
    },
    dominantWaitMinutes: 15,
    typicalWaitMinutes: 12,
    lastUpdated: new Date(Date.now() - 300000).toISOString(),
    coordinates: { lat: 32.5694, lng: -116.6333 },
    restrictions: {
      commercialAllowed: true,
      pedestrianAllowed: true,
      specialNotices: ["SENTRI lanes not available"],
    },
    historicalHourlyProfile: Array.from({ length: 24 }, (_, i) => ({
      hour: i,
      typicalWait: Math.round(8 + 15 * Math.sin((i - 6) * (Math.PI / 12))),
    })),
  },
];

// ─── Mock Data: Recommendation ───
export function getMockRecommendation(
  origin: string = "Tijuana",
  destination: string = "San Diego"
): LegacyCrossingRecommendation {
  return {
    tripId: "mock-trip-1",
    originName: origin,
    destinationName: destination,
    direction: "MX_TO_US",
    selectedCrossingId: "otay-mesa",
    fastestCrossingName: "Otay Mesa",
    borderWaitMinutes: 35,
    approachTransitMinutes: 8,
    totalEstimatedMinutes: 43,
    evidence: [
      "Shortest border wait (35 min vs 45 min at San Ysidro)",
      "Fastest total journey (43 min)",
      "All required lanes available",
    ],
    alternatives: [
      {
        crossingId: "san-ysidro",
        crossingName: "San Ysidro",
        totalEstimatedMinutes: 52,
        deltaMinutes: 9,
      },
      {
        crossingId: "tecate",
        crossingName: "Tecate",
        totalEstimatedMinutes: 58,
        deltaMinutes: 15,
      },
    ],
    generatedAt: new Date().toISOString(),
  };
}

// ─── Mock Data: Alerts ───
export const MOCK_ALERTS: BorderAlertEvent[] = [
  {
    id: "alert-1",
    crossingId: "san-ysidro",
    crossingName: "San Ysidro",
    direction: "MX_TO_US",
    timestamp: new Date(Date.now() - 900000).toISOString(),
    type: "QUEUE_SURGE",
    severity: "IMPORTANT",
    headline: "Wait increased 30 → 45 min",
    description:
      "Standard lane wait times at San Ysidro have surged significantly.",
    previousValue: "30 min",
    currentValue: "45 min",
  },
  {
    id: "alert-2",
    crossingId: "otay-mesa",
    crossingName: "Otay Mesa",
    direction: "MX_TO_US",
    timestamp: new Date(Date.now() - 3600000).toISOString(),
    type: "LANE_STATUS_CHANGE",
    severity: "NOTABLE",
    headline: "Ready Lane reopened",
    description: "Ready Lane at Otay Mesa is now accepting traffic.",
  },
  {
    id: "alert-3",
    crossingId: "san-ysidro",
    crossingName: "San Ysidro",
    direction: "MX_TO_US",
    timestamp: new Date(Date.now() - 7200000).toISOString(),
    type: "LANE_STATUS_CHANGE",
    severity: "NORMAL",
    headline: "SENTRI lane count reduced",
    description: "SENTRI lanes reduced from 3 to 2 for maintenance.",
    previousValue: "3 lanes",
    currentValue: "2 lanes",
  },
];
